// Code generated by "stringer -type Level -trimprefix Level"; DO NOT EDIT.

package log

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LevelNONE-0]
	_ = x[LevelFATAL-1]
	_ = x[LevelERROR-2]
	_ = x[LevelWARN-3]
	_ = x[LevelINFO-4]
	_ = x[LevelDEBUG-5]
	_ = x[LevelFINE-6]
}

const _Level_name = "NONEFATALERRORWARNINFODEBUGFINE"

var _Level_index = [...]uint8{0, 4, 9, 14, 18, 22, 27, 31}

func (i Level) String() string {
	if i >= Level(len(_Level_index)-1) {
		return "Level(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Level_name[_Level_index[i]:_Level_index[i+1]]
}
